### ISSUE TITLE
logsniffer config.properties

### ISSUE THREAD

**Issue by tschinz** [logsniffer/logsniffer#58]
what kind of configuration can be stored in the config.properties.

I'm installing the logsniffer on many PC's and would like to setup log sources and sniffer automatically without entering them each time in the webgui.
Can this be done with the config.properties file?

thanks and kind reagards

**Comment by mbok** [comment]
The config.properties contains system settings for logsniffer like ports, hosts etc. Thus it can't be used for passing data to setup sources and sniffers.
If I understand your needs correct you like to clone the same setup regarding sources and sniffers to multiple nodes. The simplest way to do that is:
1. Setup the sources and sniffers on a reference node
2. Shutdown logsniffer on this node after finishing and copy the folder `${logsniffer.home}/h2` to each node you like to have the same setup

Without the deep know about your log management scenario I could imagine that a central log management approach could solve your problems too. Instead of distributing logsniffer and the setup across multiple nodes I'm always a fan of forwarding logs from multiple nodes to a central log server with a central logsniffer installation and setup. In the case this scenario is applicable for you please check my blog post for a [central log management recipe](http://www.logsniffer.com/central-log-management-recipe/).

**Comment by tschinz** [comment]
Hello mbok that's exactly what I had in mind. The central log is only partly applicable because we have machines with multiple pc which can have one central log management but each machine needs such a setup, they can't communicate to a really central log server. 
When I can copy the logsniffer.home folder then it's absolutely fine.

Thanks again for your help and the great and simple application you've build. (Thumbs up)
